### ISSUE TITLE
Permissions Issue on Install

### ISSUE THREAD

**Issue by glimmung** [collective/rapido.plone#21]
Installed using plain Plone 5.0.6 (no other add ons) with only rapido.plone added to default buildout from unified installer, errors on startup with: -

instance: Traceback (most recent call last):
  File "/opt/Plone/506-rapido/zinstance/bin/instance", line 269, in <module>
    import plone.recipe.zope2instance.ctl
  File "/opt/Plone/506-rapido/buildout-cache/eggs/plone.recipe.zope2instance-4.2.21-py2.7.egg/plone/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3013, in <module>
    @_call_aside
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3041, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2571, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2561, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1467, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1463, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/opt/Plone/506-rapido/zinstance/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1572, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/opt/Plone/506-rapido/buildout-cache/eggs/node-0.9.16-py2.7.egg/EGG-INFO/namespace_packages.txt

Will try sort permissions, but thought I should report.

**Comment by danboggins** [comment]
This happens on Plone 5.0.1 and 5.0.3 also, I just usually just chown plone_buildout:plone_group them (there's a few files, maybe around 6 or 7 that this happens to and they're all empty as far as I know).

**Comment by ebrehault** [comment]
It is not related to Rapido but to your install (and it would probably do the same if try to install any other add-ons).
Just check your current system user access.

**Comment by glimmung** [comment]
@ebrehault  - /most/ other products are fine, but you are right, not just rapido. However, in this case simply adding Rapido to a completely vanila, virgin install triggered it, which is why I reported it.

I did: -

sudo chmod -R g+r /opt/Plone/506-rapido/buildout-cache

...and now have a running Plone - have seen this before but discarded the problem products, so will revisit them. Definitely a Plone "papercut".

**Comment by ebrehault** [comment]
It should not happen if you run your buildout with the same user you used to run the Unified installer.

**Comment by glimmung** [comment]
Not sure I understand, in the sense that buildout is run as plone_buildout, which is created by the installer, which was run with sudo. I followed the install docs exactly, so "sudo /.install.sh" etc. for a root install, and then "sudo -u plone_buildout bin/buildout". 

To be clear, I am happily up and running now, and only reporting this in case I am misunderstanding you.

**Comment by ebrehault** [comment]
ok, well, I don't know then... (actually I never use Unified Installer in sudo)

**Comment by glimmung** [comment]
I'm starting to suspect that the unified installer (or possibly its sudo behaviour) is the issue. Thanks for your help!
